### ISSUE TITLE
图形验证未通过

### ISSUE THREAD

**Issue by TimeJason** [arlettebrook/autoCheck-in#1]
日志中提示图形验证未通过，我想要在cookie中加入vdevice_qimei36='...'，但是奈何找不到这个cookie，大佬能不能展开说说怎么找这个cookie

**Comment by arlettebrook** [comment]
不是所有帐号都能签到成功因为有的帐号会触发滑块认证或者短信验证

使用常用手机打开后面的连接，注意是https，成功进入之后点击查看设备信息，QIMEI36字段就是vdevice_qimei36='...'，按照cookie格式加在LOGIN_COOKIE末尾即可。

注意：如果你平时签到之类的都需要验证码和滑块验证，加上这个字段之后并不能解决问题。目前部分账号会出现安全验证。
